CREATE TYPE "public"."user_role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"action" varchar(80) NOT NULL,
	"actorType" varchar(32) NOT NULL,
	"actorId" varchar(80) NOT NULL,
	"payloadJson" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bot_configs" (
	"id" integer PRIMARY KEY NOT NULL,
	"configVersion" integer NOT NULL,
	"isPaused" boolean DEFAULT false NOT NULL,
	"watchlistJson" text NOT NULL,
	"timeframesJson" text NOT NULL,
	"ruleFamiliesJson" text NOT NULL,
	"enabledPatternsJson" text NOT NULL,
	"enabledMethodologiesJson" text NOT NULL,
	"liveAlertsJson" text NOT NULL,
	"alertThreshold" double precision NOT NULL,
	"cooldownMinutes" integer NOT NULL,
	"quietHoursJson" text NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candle_history" (
	"id" varchar(96) PRIMARY KEY NOT NULL,
	"assetSymbol" varchar(32) NOT NULL,
	"venue" varchar(64) NOT NULL,
	"timeframe" varchar(12) NOT NULL,
	"candleCloseTime" timestamp with time zone NOT NULL,
	"open" double precision NOT NULL,
	"high" double precision NOT NULL,
	"low" double precision NOT NULL,
	"close" double precision NOT NULL,
	"volume" double precision NOT NULL,
	"ema20" double precision NOT NULL,
	"ema50" double precision NOT NULL,
	"ema200" double precision NOT NULL,
	"rsi14" double precision NOT NULL,
	"macd" double precision NOT NULL,
	"macdSignal" double precision NOT NULL,
	"atr14" double precision NOT NULL,
	"signalState" varchar(32) NOT NULL,
	"signalScore" double precision NOT NULL,
	"strategyVersion" varchar(32) NOT NULL,
	"configVersion" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dashboard_credentials" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboard_credentials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(64) NOT NULL,
	"passwordHash" varchar(255) NOT NULL,
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dashboard_credentials_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "dashboard_sessions" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"credentialId" integer NOT NULL,
	"tokenHash" varchar(64) NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"lastSeenAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dashboard_sessions_tokenHash_unique" UNIQUE("tokenHash")
);
--> statement-breakpoint
CREATE TABLE "live_observations" (
	"id" varchar(96) PRIMARY KEY NOT NULL,
	"assetSymbol" varchar(32) NOT NULL,
	"observedAt" timestamp with time zone NOT NULL,
	"conditionId" varchar(64) NOT NULL,
	"direction" varchar(16) NOT NULL,
	"score" double precision NOT NULL,
	"dataQualityState" varchar(32) NOT NULL,
	"evidenceJson" text NOT NULL,
	"sourceEventIdsJson" text NOT NULL,
	"configVersion" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "market_archive_manifests" (
	"id" varchar(96) PRIMARY KEY NOT NULL,
	"streamType" varchar(24) NOT NULL,
	"assetSymbol" varchar(32) NOT NULL,
	"partitionStart" timestamp with time zone NOT NULL,
	"partitionEnd" timestamp with time zone NOT NULL,
	"objectKey" varchar(512) NOT NULL,
	"rowCount" integer NOT NULL,
	"sha256" varchar(64) NOT NULL,
	"clickhouseBatchId" varchar(96) NOT NULL,
	"state" varchar(24) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "market_archive_manifests_objectKey_unique" UNIQUE("objectKey")
);
--> statement-breakpoint
CREATE TABLE "market_pipeline_health" (
	"component" varchar(24) PRIMARY KEY NOT NULL,
	"state" varchar(24) NOT NULL,
	"lastSuccessAt" timestamp with time zone,
	"lastError" text,
	"lagMs" integer,
	"summaryJson" text NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "runner_health" (
	"id" integer PRIMARY KEY NOT NULL,
	"runId" varchar(64),
	"state" varchar(24) NOT NULL,
	"configVersion" integer,
	"startedAt" timestamp with time zone,
	"finishedAt" timestamp with time zone,
	"cycleCount" integer DEFAULT 0 NOT NULL,
	"failureCount" integer DEFAULT 0 NOT NULL,
	"lastError" text,
	"summaryJson" text NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "signal_snapshots" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"assetSymbol" varchar(32) NOT NULL,
	"venue" varchar(64) NOT NULL,
	"timeframe" varchar(12) NOT NULL,
	"candleCloseTime" timestamp with time zone NOT NULL,
	"state" varchar(32) NOT NULL,
	"score" double precision NOT NULL,
	"confidence" double precision NOT NULL,
	"regime" varchar(32) NOT NULL,
	"dataQualityState" varchar(32) NOT NULL,
	"findingsJson" text NOT NULL,
	"conflictsJson" text NOT NULL,
	"invalidationJson" text NOT NULL,
	"strategyVersion" varchar(32) NOT NULL,
	"configVersion" integer NOT NULL,
	"sourceManifestId" varchar(64) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "telegram_polling_state" (
	"id" integer PRIMARY KEY NOT NULL,
	"updateOffset" integer DEFAULT 0 NOT NULL,
	"lastPolledAt" timestamp with time zone,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
--> statement-breakpoint
CREATE INDEX "audit_events_created_idx" ON "audit_events" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "candle_history_asset_time_idx" ON "candle_history" USING btree ("assetSymbol","timeframe","candleCloseTime");--> statement-breakpoint
CREATE INDEX "candle_history_created_idx" ON "candle_history" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "dashboard_credentials_username_idx" ON "dashboard_credentials" USING btree ("username");--> statement-breakpoint
CREATE INDEX "dashboard_sessions_credential_idx" ON "dashboard_sessions" USING btree ("credentialId");--> statement-breakpoint
CREATE INDEX "dashboard_sessions_expiry_idx" ON "dashboard_sessions" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "live_observations_asset_time_idx" ON "live_observations" USING btree ("assetSymbol","observedAt");--> statement-breakpoint
CREATE INDEX "market_archive_manifests_partition_idx" ON "market_archive_manifests" USING btree ("assetSymbol","partitionStart");--> statement-breakpoint
CREATE INDEX "market_pipeline_health_state_updated_idx" ON "market_pipeline_health" USING btree ("state","updatedAt");--> statement-breakpoint
CREATE INDEX "runner_health_updated_idx" ON "runner_health" USING btree ("updatedAt");--> statement-breakpoint
CREATE INDEX "signal_snapshots_asset_time_idx" ON "signal_snapshots" USING btree ("assetSymbol","timeframe","candleCloseTime");--> statement-breakpoint
CREATE INDEX "signal_snapshots_created_idx" ON "signal_snapshots" USING btree ("createdAt");